# Generated by Django 5.0.2 on 2024-04-12 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_farmerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetails',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Farmer'}, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
        ),
    ]
