# Generated by Django 5.0.2 on 2024-04-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_farmerdetails_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phoneneumber',
            new_name='phonenumber',
        ),
    ]
