# Generated by Django 5.0.2 on 2024-04-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='farmerdetails',
            old_name='overallrating',
            new_name='farmer_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-16 17:22:16.993715'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Farmer'}, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
        ),
    ]
