# Generated by Django 5.0.2 on 2024-04-22 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_search_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetails',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'Farmer'}, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
