# Generated by Django 5.0.2 on 2024-04-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_sold_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(blank=True, default='images/user/default_user_image.png', null=True, upload_to='images/user'),
        ),
    ]
