RESPONSES = {
    "hi": "Hello! How can I help you today?",
    "hai": "Hi! Welcome to FarmCart. How may I help you?",
    "need help": "Sure, I'm here to help! What do you need?",
    "how to cancel my order": "To cancel your order, please go to your orders page, select the order and click on 'Cancel'.",
    "connect me with your customer care": "Your complaint has been registered and our team will contact you shortly.",
    "where do you deliver": "We deliver to all major cities across the country. You can specify your location to see if we deliver to your area!",
    "how to change delivery address": "You can change your delivery address from your account settings or during the checkout before finalizing your order.",
    "what are your delivery times": "Our delivery times are from 8 AM to 6 PM on weekdays. Weekend deliveries vary based on your location.",
    "do you have organic carrots": "Yes, we have organic carrots available! You can add them to your cart directly from the 'Vegetables' section.",
    "how to apply a promo code": "You can apply a promo code at the checkout page. Just enter your code in the 'Promo Code' field and click apply.",
    "are your vegetables pesticide free": "AbsolQutely! All our vegetables are 100% organic and free from any pesticides or harmful chemicals.",
    "can I pick up my order": "Yes, you can choose to pick up your order at our nearest store location. Just select 'Pick Up' option during checkout.",
    "how to track my order": "You can track your order status from your account under the 'Orders' section. We also send email updates as your order progresses!",
    "payment methods available": "We accept all major credit cards, debit cards, and mobile payments through secure online transactions.",
    "how to return an item": "To return an item, please visit your order history and select the item you wish to return. Follow the instructions provided to initiate a return.",
    "account creation benefits": "Creating an account allows you to check out faster, save multiple shipping addresses, access your order history, and manage your preferences.",
    "help with account login": "If you're having trouble logging into your account, try resetting your password or contact customer support for assistance.",
    "location based sorting": "Our website automatically sorts products based on your location to show you the freshest vegetables available in your area. Make sure your location services are enabled!",
    "what is organic farming": "Organic farming is a method of crop and livestock production that involves much more than choosing not to use pesticides, fertilizers, genetically modified organisms, antibiotics, and growth hormones. It is a holistic system designed to optimize the productivity and fitness of diverse communities within the ecosystem.",
    "benefits of organic food": "Organic foods are not just good for the body, but they're also good for the environment. They reduce pollutants in groundwater and create richer soil that aids plant growth while reducing erosion. It also means safer working conditions for farmers and the reduction of greenhouse gases.",
    "how do we ensure organic integrity": "Our farms are certified organic following stringent standards that assure the organic integrity of our products from the farm to your table. This includes regular inspections and detailed record-keeping.",
    "why are organic products more expensive": "Organic foods are more labor-intensive since the farmers do not use pesticides, chemical fertilizers, or drugs. Organic certification is expensive and organic feed for animals can cost twice as much.",
    "do organic farmers use pesticides": "Organic farmers use natural pesticides approved for organic farming. They also use beneficial insects and birds, mating disruption or traps to manage pests and diseases.",
    "how to store organic vegetables": "Keep your organic vegetables in a cool, dry place. For leafy greens, wrap them in a damp cloth and store in the refrigerator to maintain freshness.",
    "is organic food really better for you": "Many studies have shown that organic foods contain more beneficial nutrients, such as antioxidants, than their conventionally grown counterparts. Moreover, people with allergies to foods, chemicals, or preservatives often find their symptoms lessen or go away when they eat only organic foods.",
    "what are the benefits of organic farming": "Organic farming promotes soil health, biodiversity, and environmental sustainability by avoiding the use of synthetic pesticides and fertilizers.",
    "what are the advantages of organic food": "Organic food benefits include higher nutrient content, reduced exposure to harmful chemicals, and support for sustainable agricultural practices.",
    "is there scientific evidence supporting the health benefits of organic food": "Numerous studies suggest that organic food contains higher levels of beneficial nutrients and lower levels of harmful chemicals, making it a healthier choice for consumers.",
    "what is the recommended method for storing organic vegetables": "To maintain freshness, store organic vegetables in a cool, dry place or refrigerate leafy greens wrapped in a damp cloth.",
    "Can I request a customized vegetable box?":"Yes, we offer customizable vegetable boxes where you can select your preferred vegetables. Please contact our customer support team to place a customized order.",
    "How often do you restock your inventory?":"We restock our inventory regularly to ensure a continuous supply of fresh organic produce. New items are added as soon as they become available.",
    "Do you offer any rewards or loyalty programs?":"Yes, we have a loyalty program where you can earn points for every purchase. These points can be redeemed for discounts on future orders.",
    "Can I request a refund if I'm not satisfied with my order?":"Yes, we offer a satisfaction guarantee. If you're not satisfied with your order, please reach out to our customer support team within the specified return window for assistance.",
    "Are your packaging materials eco-friendly?":"Yes, we strive to use eco-friendly packaging materials whenever possible to minimize environmental impact.",
    "Do you offer bulk discounts for large orders?":"Yes, we offer discounts on bulk orders. Please contact our customer support team for more information on bulk pricing.",
    "Are your products locally sourced?":"Yes, we prioritize sourcing from local farmers to provide you with the freshest organic produce while supporting the local agricultural community.",
    "I'm looking for organic tomatoes. Do you have them?":"Yes, we have organic tomatoes available. You can find them in the 'Vegetables' section of our app.",
    "Do you deliver to rural areas?":"Yes, we deliver to both urban and rural areas. Please specify your location during checkout to confirm delivery availability in your area.",
    "Are your products certified organic?":"Yes, all our products are certified organic, ensuring high-quality, chemical-free produce.",
    "Do you offer international shipping?":"At the moment, we only offer domestic shipping within the country. We're working on expanding our shipping capabilities in the future.",
    "What precautions do you take to ensure food safety?":"We follow strict food safety guidelines and regularly sanitize our facilities to ensure the highest standards of hygiene and cleanliness.",
    "Do you offer cooking tips for your products?":"Yes, we provide cooking tips and recipe ideas on our website and social media channels to help you make the most of your fresh produce.",
    "What measures do you take to reduce food waste?":"We minimize food waste by optimizing inventory management, donating excess food to local charities, and promoting responsible consumption practices.",
    "Do you offer nutritional information for your products?":"Yes, we provide nutritional information for our products on our website and product packaging to help you make informed dietary choices.",
    "Can I request a sample of a product before purchasing?":"Unfortunately, we do not offer product samples at this time. However, you can check customer reviews and ratings to learn more about the quality of our products.",
    "what is your privacy policy": "Our privacy policy outlines how we collect, use, and protect your personal information. You can review our Privacy Policy page for more details.",
    "do you offer subscription services": "Yes, we offer subscription services for certain products. You can subscribe to receive regular deliveries of your favorite items at a discounted price.",
    "what packaging materials do you use": "We use eco-friendly packaging materials whenever possible to minimize our environmental impact. Our packaging is recyclable and biodegradable.",
    "how do I know if a product is in stock": "You can check the availability of a product by visiting its product page on our website. If a product is out of stock, you will see a notification indicating its availability status.",
    "what is your commitment to customer satisfaction": "We are committed to providing exceptional customer service and ensuring your satisfaction with every purchase. If you're not completely satisfied, please contact us and we'll do our best to make it right.",
     "how do I check my order history": "You can check your order history by logging into your account and navigating to the 'Order History' or 'My Orders' section. Here, you'll find a list of all your past orders and their statuses.",
    "what do I do if I forget my password": "If you forget your password, you can reset it by clicking on the 'Forgot Password' link on the login page. Follow the prompts to reset your password and regain access to your account.",
     "how do I update my account information": "You can update your account information by logging into your account and navigating to the 'Account Settings' or 'Profile' section. Here, you can edit your personal information, shipping addresses, and communication preferences.",
    "do you offer product samples": "Yes, we offer product samples for certain items. Contact our customer support team to inquire about sample availability and pricing.",
    "what is your commitment to product safety": "We are committed to product safety and compliance with regulatory standards. Our products undergo rigorous testing and quality assurance measures to ensure they meet safety requirements and industry standards.",
    "how do I know if a product is backordered": "If a product is backordered, you will see a notification indicating its availability status on the product page. You can also contact our customer support team for more information about backordered items.",
    "what do I do if I experience technical issues on the website": "If you experience technical issues on our website, please try clearing your browser cache and cookies or using a different browser. If the problem persists, contact our customer support team for assistance.",
    "do you offer product recommendations": "Yes, we offer personalized product recommendations based on your past purchases and browsing history. You can find recommended products on your account dashboard or product pages.",
    "what is your commitment to product transparency": "We are committed to product transparency and providing accurate information about our products. We disclose ingredients, sourcing, and manufacturing details to help you make informed purchasing decisions.",
    "how do I redeem a gift card": "You can redeem a gift card during checkout by entering the gift card code in the designated field. The gift card amount will be applied to your total order value.",
    "what do I do if I have an allergic reaction to a product": "If you have an allergic reaction to a product, stop using it immediately and seek medical attention if necessary. Contact our customer support team to report the incident and discuss options for a refund or replacement.",
    "do you offer product subscriptions": "Yes, we offer product subscriptions for certain items. You can subscribe to receive regular deliveries of your favorite products on a schedule that works for you.",
    "what is your commitment to inclusivity and diversity": "We are committed to inclusivity and diversity in all aspects of our business. We strive to create a welcoming and inclusive environment for all customers, employees, and partners.",
    "how do I request a price match": "To request a price match, contact our customer support team with evidence of the lower price from a reputable competitor. We'll review the request and adjust the price if it meets our price match criteria.",
    "what do I do if I receive a defective product": "If you receive a defective product, please contact our customer support team immediately. We'll arrange for a replacement or refund and provide instructions for returning the defective item.",
    "do you offer product warranties": "Yes, we offer warranties for certain products. Check the product page or packaging for warranty information, or contact our customer support team for assistance with warranty claims.",
    "what is your commitment to data privacy": "We are committed to protecting your data privacy and security. We adhere to strict data protection regulations and implement robust security measures to safeguard your personal information.",
    "how do I know if a product is cruelty-free": "Products labeled as cruelty-free are not tested on animals. Look for certifications or labels indicating cruelty-free status, or check the product description for information about animal testing.",
    "what do I do if I receive an incorrect order": "If you receive an incorrect order, please contact our customer support team immediately. We'll arrange for the correct items to be sent to you and provide instructions for returning the incorrect items.",
    "do you offer product recycling programs": "Yes, we offer product recycling programs for certain items. Check the product page or packaging for recycling instructions, or contact our customer support team for assistance with recycling.",
    "what is your commitment to customer empowerment": "We are committed to empowering our customers with the knowledge and resources they need to make informed decisions about their purchases. We provide educational materials, product information, and personalized support to help you find the products that best meet your needs.",
    "how do I know if a product is fair trade": "Products labeled as fair trade adhere to fair trade standards, which include fair wages, safe working conditions, and sustainable practices. Look for certifications or labels indicating fair trade status, or check the product description for information about fair trade sourcing.",
    "what do I do if I accidentally place an order": "If you accidentally place an order, please contact our customer support team immediately. We'll do our best to cancel the order before it ships, or provide instructions for returning the items if necessary.",
    "do you offer bulk ordering options": "Yes, we offer bulk ordering options for certain products. Contact our customer support team to inquire about bulk pricing, minimum order quantities, and delivery options.",
    "what is your commitment to product innovation": "We are committed to product innovation and continuously strive to bring you new and exciting products that meet your evolving needs. We invest in research and development to create innovative solutions that enhance your quality of life.",
    "how do I know if a product is non-GMO": "Products labeled as non-GMO are free from genetically modified organisms. Look for certifications or labels indicating non-GMO status, or check the product description for information about GMO-free ingredients.",
    "what do I do if I need to make changes to my order": "If you need to make changes to your order, please contact our customer support team as soon as possible. We'll do our best",
    "hello": "Hi! Welcome to FarmCart. How may I help you?",
    "hlo": "Hi! Welcome to FarmCart. How may I help you?",
    "hey": "Hey! What can I do for you today?",
    "hi there": "Hello! How can I assist you with your farming needs?",
    "howdy": "Howdy! What brings you to FarmCart today?",
    "good morning": "Good morning! Welcome to FarmCart. How can I assist you?",
    "good afternoon": "Good afternoon! How may I help you with your farming requirements?",
    "good evening": "Good evening! Welcome to FarmCart. What can I assist you with?",
    "greetings": "Greetings! How can I be of service to you today?",
    "hi, how are you?": "Hi! I'm doing well, thank you. How can I assist you today?",
    "hello, what's up?": "Hello! Not much, just here to help you with any farming inquiries you have.",
    "hi, is anyone there?": "Hi! Yes, I'm here. How can I assist you today?",
    "hello, can I get some help?": "Hello! Of course, I'm here to help. What do you need assistance with?",
    "hi, I'm new here.": "Hi and welcome to FarmCart! Feel free to ask if you need any assistance navigating our platform.",
    "hello, I have a question.": "Hello! Please go ahead and ask your question, I'm here to help.",
    "hi, can you help me with something?": "Hi! Absolutely, just let me know what you need assistance with.",
    "hello, I'm looking for some information.": "Hello! I'm here to provide any information you need. What are you looking for?",
    "hi, do you offer farming services?": "Hi! Yes, we offer various farming services. What specifically are you interested in?",
    "hello, are you the right person to ask about farming tools?": "Hello! Yes, I can assist you with information about farming tools. What do you need to know?",
    "hi, can I find organic seeds here?": "Hi! Yes, we offer a selection of organic seeds. What type of seeds are you looking for?",
    "good morning": "Good morning! Welcome to FarmCart. How can I help you today?",
    "good afternoon": "Good afternoon! How can I assist you with FarmCart?",
    "good evening": "Good evening! Welcome to FarmCart. What can I do for you?",
    "hiya": "Hiya! It's great to see you at FarmCart. How may I assist you today?",
    "yo": "Yo! Welcome to FarmCart. What do you need assistance with?",
    "how's it going": "Hello! I'm here to help you with anything you need at FarmCart. What can I assist you with today?",
    "what's up": "Hey there! Welcome to FarmCart. How can I help you today?",
    "how can I help you": "Hello! I'm here to assist you with anything you need at FarmCart. What can I help you with?",
    "need assistance": "Hi there! I'm here to assist you. How can I help you with FarmCart?",
    "any questions": "Hello! Feel free to ask if you have any questions about FarmCart. I'm here to help!",
    "here to help": "Hi! I'm here to help you with FarmCart. What do you need assistance with?",
    "how can I assist you": "Hello! How can I assist you with FarmCart today?",
    "what can I do for you": "Hi there! What can I do for you today on FarmCart?",
    "anything I can help with": "Hello! Is there anything specific I can assist you with today on FarmCart?",
    "what's on your mind": "Hi! What's on your mind today regarding FarmCart? I'm here to help!",
    "what do you need help with": "Hello! What do you need assistance with on FarmCart? I'm here to help!",
    "what brings you here": "Hi there! What brings you to FarmCart today? How can I assist you?",
    "how can I be of service": "Hello! How can I be of service to you today on FarmCart?",
    "how can I be of assistance": "Hi! How can I be of assistance to you today on FarmCart?",
    "what brings you to FarmCart": "Hello! What brings you to FarmCart today? How can I assist you?",
    "welcome to FarmCart": "Hi! Welcome to FarmCart. How can I assist you with your shopping today?",
    "nice to meet you": "Nice to meet you too! How can I assist you with FarmCart?",
    "glad to have you here": "Thank you! I'm glad to be here. How can I help you with FarmCart?",
    "pleasure to assist you": "The pleasure is mine! How can I assist you with FarmCart today?",
    "great to see you": "Great to see you too! How can I assist you with FarmCart?",
    "how can I assist you today": "Hello! How can I assist you today with FarmCart?",
    "how can I assist you right now": "Hi! How can I assist you right now with FarmCart?",
    "what can I do for you today": "Hello! What can I do for you today on FarmCart?",
    "what can I help you with today": "Hi there! What can I help you with today on FarmCart?",
    "what can I help you with right now": "Hello! What can I help you with right now on FarmCart?",
    "what can I do for you right now": "Hi! What can I do for you right now on FarmCart?",
    "how may I assist you today": "Hello! How may I assist you today with FarmCart?",
    "how may I assist you right now": "Hi there! How may I assist you right now with FarmCart?",
    "how may I help you today": "Hello! How may I help you today with FarmCart?",
    "how may I help you right now": "Hi there! How may I help you right now with FarmCart?"


}

